services:
  db:
    image: postgres:17.2
    container_name: fitomenu_db
    restart: always
    environment:
      POSTGRES_DB: ${DATABASE_NAME}
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
    ports:
      - "${DATABASE_HOST}:${DATABASE_PORT}:5432"
    volumes:
      - ./docker/postgres/data:/var/lib/postgresql/data
      - ./sql/docker:/docker-entrypoint-initdb.d
    command:
      - "postgres"
      - "-c"
      - "timezone=America/El_Salvador"
