# Generated by Django 5.1.5 on 2025-04-11 18:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("admin_panel", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="RestauranteInfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=255)),
                ("eslogan", models.CharField(blank=True, max_length=255)),
                ("historia", models.TextField(blank=True)),
                ("iframe_ubicacion", models.TextField(blank=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Información del Restaurante",
                "verbose_name_plural": "Información del Restaurante",
            },
        ),
    ]
