# Generated by Django 5.1.5 on 2025-04-11 18:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("admin_panel", "0002_restauranteinfo"),
    ]

    operations = [
        migrations.AddField(
            model_name="restauranteinfo",
            name="facebook_url",
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name="restauranteinfo",
            name="instagram_url",
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name="restauranteinfo",
            name="ubicacion",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
