# Generated by Django 5.1.5 on 2025-03-12 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0002_categoriaproducto_remove_producto_descripcion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoriaproducto',
            name='disponible',
            field=models.BooleanField(default=True),
        ),
    ]
