# Generated by Django 5.1.5 on 2025-04-29 21:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("admin_panel", "0003_restauranteinfo_facebook_url_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="restauranteinfo",
            name="correo",
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name="restauranteinfo",
            name="telefono",
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
