# Generated by Django 5.1.5 on 2025-04-30 15:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("admin_panel", "0004_restauranteinfo_correo_restauranteinfo_telefono"),
    ]

    operations = [
        migrations.AddField(
            model_name="orden",
            name="tipo",
            field=models.CharField(
                choices=[("A", "Atención"), ("P", "Para llevar")],
                default="A",
                max_length=1,
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="orden",
            name="orden",
            field=models.CharField(max_length=10),
        ),
    ]
