# Generated by Django 5.1.5 on 2025-04-30 16:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("admin_panel", "0005_orden_tipo_alter_orden_orden"),
    ]

    operations = [
        migrations.AlterField(
            model_name="orden",
            name="tipo",
            field=models.CharField(
                choices=[("A", "Restaurante"), ("P", "Para llevar")], max_length=1
            ),
        ),
    ]
